// API
const API_PAGE_SIZE = 100
const API_TOTAL_PAGES = 8

// Tamanhos de pack e deck
const PACK_SIZE = 4
const CPU_DECK_SIZE = 2
const SPELLS_COUNT = 20
const PLAYER_SPELLS_COUNT = 5

// HP
const HP_BASE = 80
const HP_RANDOM_RANGE = 20

// Poder por casa
const POWER_DEFAULT = 50
const POWER_GRYFFINDOR = 90
const POWER_SLYTHERIN = 85
const POWER_HUFFLEPUFF = 75
const POWER_RAVENCLAW = 80

// Magia por espécie
const MAGIC_DEFAULT = 50
const MAGIC_HUMAN = 70
const MAGIC_HALF_GIANT = 88
const MAGIC_GIANT = 95
const MAGIC_HOUSE_ELF = 82
const MAGIC_GHOST = 60
const MAGIC_WEREWOLF = 91
const MAGIC_VAMPIRE = 87
const MAGIC_CENTAUR = 78

// Defesa por ancestralidade
const DEFENSE_DEFAULT = 50
const DEFENSE_PURE_BLOOD = 90
const DEFENSE_HALF_BLOOD = 75
const DEFENSE_MUGGLE_BORN = 70
const DEFENSE_MUGGLE = 40
const DEFENSE_SQUIB = 35

// Dano dos feitiços por categoria
const DAMAGE_DEFAULT = 30
const DAMAGE_CHARM = 45
const DAMAGE_CURSE = 90
const DAMAGE_HEX = 65
const DAMAGE_JINX = 55
const DAMAGE_SPELL = 50
const DAMAGE_TRANSFIGURATION = 40
const DAMAGE_COUNTER_SPELL = 35
const DAMAGE_HEALING = -40

module.exports = {
  API_PAGE_SIZE,
  API_TOTAL_PAGES,
  PACK_SIZE,
  CPU_DECK_SIZE,
  SPELLS_COUNT,
  PLAYER_SPELLS_COUNT,
  HP_BASE,
  HP_RANDOM_RANGE,
  POWER_DEFAULT,
  POWER_GRYFFINDOR,
  POWER_SLYTHERIN,
  POWER_HUFFLEPUFF,
  POWER_RAVENCLAW,
  MAGIC_DEFAULT,
  MAGIC_HUMAN,
  MAGIC_HALF_GIANT,
  MAGIC_GIANT,
  MAGIC_HOUSE_ELF,
  MAGIC_GHOST,
  MAGIC_WEREWOLF,
  MAGIC_VAMPIRE,
  MAGIC_CENTAUR,
  DEFENSE_DEFAULT,
  DEFENSE_PURE_BLOOD,
  DEFENSE_HALF_BLOOD,
  DEFENSE_MUGGLE_BORN,
  DEFENSE_MUGGLE,
  DEFENSE_SQUIB,
  DAMAGE_DEFAULT,
  DAMAGE_CHARM,
  DAMAGE_CURSE,
  DAMAGE_HEX,
  DAMAGE_JINX,
  DAMAGE_SPELL,
  DAMAGE_TRANSFIGURATION,
  DAMAGE_COUNTER_SPELL,
  DAMAGE_HEALING,
}
